# Generated by Django 2.0.4 on 2018-05-04 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_estadoContrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ContratoEstado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Propiedad'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='id_tipoPropiedad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.TipoPropiedad'),
        ),
    ]
